branches:
  only:
    - main
language: node_js
node_js:
  - 16

services:
  - docker

script:
## Build
  - docker-compose -f docker-compose-build.yaml build
## Tagging
  - docker tag udagram-api-feed nvnhan/udagram-api-feed:latest
  - docker tag udagram-api-user nvnhan/udagram-api-user:latest
  - docker tag udagram-frontend nvnhan/udagram-frontend:latest
  - docker tag reverseproxy nvnhan/reverseproxy:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
## Push
  - docker push nvnhan/udagram-api-feed
  - docker push nvnhan/udagram-api-user
  - docker push nvnhan/udagram-frontend
  - docker push nvnhan/reverseproxy